### ISSUE TITLE
Add a DI container so that the commands can be broken up into smaller parts

### ISSUE THREAD

**Issue by CiderAndWhisky** [icanhazstring/duck-pony#13]

**Comment by icanhazstring** [comment]
Probably adding a simple container from `league/container` would be nice to have with autowiring. So no big configs have to be created.

The container should be configured inside the `bin/dp` (https://github.com/icanhazstring/duck-pony/blob/master/bin/dp) file where the commands are added.
Here the `Application` should be created and the commands should be retrieved from the container, instead of created a new instance inline.

See docs here: https://container.thephpleague.com/3.x/auto-wiring/
